# Generated by Django 3.1.7 on 2021-03-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_email', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactemail',
            options={'ordering': ['name'], 'verbose_name': 'Email', 'verbose_name_plural': 'Emails'},
        ),
    ]
