# Generated by Django 3.1.7 on 2021-03-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact_email', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('emails', models.ManyToManyField(to='contact_email.ContactEmail')),
            ],
            options={
                'verbose_name': 'Lista de Email',
                'verbose_name_plural': 'Listas de Emails',
                'ordering': ['name'],
            },
        ),
    ]
