# Generated by Django 3.1.7 on 2021-03-15 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillist',
            old_name='descricao',
            new_name='description',
        ),
    ]
