# Generated by Django 3.1.7 on 2021-03-16 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_remove_message_recipint_list'),
        ('email_list', '0002_auto_20210315_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillist',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='message.message'),
            preserve_default=False,
        ),
    ]
