# Generated by Django 3.1.7 on 2021-03-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_list', '0003_emaillist_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillist',
            name='message',
        ),
    ]
