# Generated by Django 3.1.7 on 2021-03-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_email',
            field=models.EmailField(default=1, max_length=254, verbose_name='De '),
            preserve_default=False,
        ),
    ]
