# Generated by Django 3.1.7 on 2021-03-16 11:33

from django.db import migrations, models
import email_manager.email_list.models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_sender_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipente_list',
            field=models.EmailField(default=1, max_length=254, verbose_name=email_manager.email_list.models.EmailList),
            preserve_default=False,
        ),
    ]
