# Generated by Django 3.1.7 on 2021-03-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_message_email_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='email_list',
        ),
    ]
