# Generated by Django 3.1.7 on 2021-03-16 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_list', '0004_remove_emaillist_message'),
        ('message', '0007_remove_message_email_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='email_list.emaillist'),
            preserve_default=False,
        ),
    ]
